{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ai-compare.fullname" . }}-load-simulator
  labels:
    {{- include "ai-compare.labels" . | nindent 4 }}
    app.kubernetes.io/component: load-simulator
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "ai-compare.fullname" . }}-load-simulator
  template:
    metadata:
      labels:
        app: {{ include "ai-compare.fullname" . }}-load-simulator
        {{- with .Values.frontend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.frontend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: load-simulator
          image: "{{ .Values.frontend.loadSimulator.image.repository }}:{{ .Values.frontend.loadSimulator.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          {{- with .Values.frontend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: TARGET_URL
              value: "http://{{ include "ai-compare.fullname" . }}-app-service:8080"
            - name: INTERVAL_SECONDS
              value: {{ .Values.frontend.loadSimulator.intervalSeconds | quote }}
            - name: LOAD_SIMULATOR_ENABLED
              value: {{ .Values.frontend.loadSimulator.enabled | quote }}
            - name: REQUEST_TIMEOUT
              value: {{ .Values.frontend.loadSimulator.requestTimeout | quote }}
            {{- if .Values.frontend.loadSimulator.customPrompts }}
            - name: LOAD_PROMPTS
              value: {{ .Values.frontend.loadSimulator.customPrompts | toJson | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          # No ports needed - this is a client, not a server
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - "import sys; sys.exit(0)"  # Simple python check
            initialDelaySeconds: 30
            periodSeconds: 60
          readinessProbe:
            exec:
              command:
                - python
                - -c
                - "import sys; sys.exit(0)"  # Simple python check
            initialDelaySeconds: 10
            periodSeconds: 30
      {{- with .Values.frontend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}