apiVersion: v1
kind: Service
metadata:
  name: ai-compare-chat-service
spec:
  selector:
    app: ai-compare-chat
  ports:
  - protocol: TCP
    port: {{ .Values.llmChat.service.port }}
    targetPort: {{ .Values.llmChat.service.port }}
    name: http
  type: {{ .Values.llmChat.service.type }}