apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-compare.fullname" . }}-chat-service
spec:
  selector:
    app: {{ include "ai-compare.fullname" . }}-chat
  ports:
  - protocol: TCP
    port: {{ .Values.llmChat.service.port }}
    targetPort: {{ .Values.llmChat.service.port }}
    name: http
  type: {{ .Values.llmChat.service.type }}