{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-compare.fullname" . }}-frontend-service
  labels:
    {{- include "ai-compare.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  annotations:
    {{- if .Values.frontend.service.annotations }}
    {{- toYaml .Values.frontend.service.annotations | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq .Values.frontend.service.type "NodePort") .Values.frontend.service.nodePort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
  selector:
    {{- include "ai-compare.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
{{- end }}