{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-compare.fullname" . }}-frontend-config
  labels:
    {{- include "ai-compare.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        # Logging
        access_log /var/log/nginx/access.log combined;
        error_log  /var/log/nginx/error.log warn;

        # Gzip compression
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        # Security headers
        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";

        upstream ai_compare_backend {
            server {{ include "ai-compare.fullname" . }}-app-service:8080;
            keepalive 32;
        }

        server {
            listen 80;
            server_name localhost;
            
            # Root directory for static files
            root /usr/share/nginx/html;
            index index.html;

            # Health check endpoint
            location /health {
                proxy_pass http://ai_compare_backend/health;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                
                # Add observability headers
                add_header X-Service-Name "{{ include "ai-compare.fullname" . }}-frontend";
                add_header X-Request-ID $request_id;
            }

            # API endpoints - proxy to backend
            location /api/ {
                proxy_pass http://ai_compare_backend/api/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header Connection "";
                proxy_http_version 1.1;
                
                # Timeouts
                proxy_connect_timeout 5s;
                proxy_send_timeout 60s;
                proxy_read_timeout 60s;
                
                # Add observability headers
                add_header X-Service-Name "{{ include "ai-compare.fullname" . }}-frontend";
                add_header X-Request-ID $request_id;
                add_header X-Backend-Service "{{ include "ai-compare.fullname" . }}-app";
            }

            # Static files
            location / {
                try_files $uri $uri/ /index.html;
                
                # Cache static assets
                location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
                    expires 1y;
                    add_header Cache-Control "public, immutable";
                }
                
                # Add security headers for HTML
                location ~* \.html$ {
                    add_header X-Service-Name "{{ include "ai-compare.fullname" . }}-frontend";
                    add_header X-Request-ID $request_id;
                    expires 0;
                    add_header Cache-Control "no-cache, no-store, must-revalidate";
                }
            }

            # Error pages
            error_page 404 /404.html;
            error_page 500 502 503 504 /50x.html;
            
            location = /50x.html {
                root /usr/share/nginx/html;
            }
            
            location = /404.html {
                root /usr/share/nginx/html;
            }

            # Deny access to hidden files
            location ~ /\. {
                deny all;
            }
        }
    }

  index.html: |
{{ .Files.Get "frontend/index.html" | indent 4 }}

  style.css: |
{{ .Files.Get "frontend/style.css" | indent 4 }}

  script.js: |
{{ .Files.Get "frontend/script.js" | indent 4 }}
{{- end }}