annotations:
  helm.sh/images: |
    - image: dp.apps.rancher.io/containers/open-webui:0.6.41-14.20
      name: open-webui
  licenses: MIT
apiVersion: v2
appVersion: 0.6.41
dependencies:
- condition: ollama.enabled
  import-values:
  - child: service
    parent: ollama.service
  name: ollama
  repository: oci://dp.apps.rancher.io/charts
  version: 1.26.0
- alias: pipelines
  condition: pipelines.enabled
  import-values:
  - child: service
    parent: pipelines.service
  name: open-webui-pipelines
  repository: oci://dp.apps.rancher.io/charts
  version: 0.5.0
- alias: tika
  condition: tika.enabled
  name: apache-tika
  repository: oci://dp.apps.rancher.io/charts
  version: 3.2.2
description: Open WebUI is an extensible, feature-rich, and user-friendly self-hosted
  WebUI designed to operate entirely offline. It supports various LLM runners, including
  Ollama and OpenAI-compatible APIs.
home: https://apps.rancher.io/applications/open-webui
icon: https://apps.rancher.io/logos/open-webui.png
keywords:
- llm
- chat
- web-ui
maintainers:
- name: SUSE LLC
  url: https://www.suse.com
name: open-webui
version: 7.3.0
