apiVersion: v1
kind: Config
clusters:
- name: "dev-ai-dino"
  cluster:
    server: "https://rancher-dino.dna-42.com/k8s/clusters/c-m-gfzfjzhv"

users:
- name: "dev-ai-dino"
  user:
    token: "kubeconfig-user-hnzj588g4g:b7kfpfmnlmpbnpgz5wf7g9dld8ng5pw47zhqzvhvn4jbjj6hhcdsmj"


contexts:
- name: "dev-ai-dino"
  context:
    user: "dev-ai-dino"
    cluster: "dev-ai-dino"

current-context: "dev-ai-dino"
