apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-compare-test-simple
  namespace: genai
  labels:
    app: ai-compare-test-simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-compare-test-simple
  template:
    metadata:
      labels:
        app: ai-compare-test-simple
    spec:
      containers:
      - name: genai-demo
        image: ravan/genai-observability-demo-app:0.0.6
        ports:
        - containerPort: 8000
        env:
        - name: APP_NAME
          value: "AICompareTestDemo"
        - name: OLLAMA_ENDPOINT
          value: "http://ollama-service:11434"
        - name: OTLP_ENDPOINT
          value: "http://opentelemetry-collector.suse-observability.svc.cluster.local:4318"
        - name: COLLECT_GPU_STATS
          value: "false"
        resources:
          requests:
            cpu: 400m
            memory: 800Mi
          limits:
            cpu: 600m
            memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ai-compare-test-simple-service
  namespace: genai
spec:
  selector:
    app: ai-compare-test-simple
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
