apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-genai-demo
  namespace: fresh
  labels:
    app: test-genai-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-genai-demo
  template:
    metadata:
      labels:
        app: test-genai-demo
    spec:
      containers:
      - name: genai-demo
        image: ravan/genai-observability-demo-app:0.0.6
        ports:
        - containerPort: 8000
        env:
        - name: APP_NAME
          value: "AICompareDemo"
        - name: OLLAMA_ENDPOINT
          value: "http://ollama-service:11434"
        - name: OTLP_ENDPOINT
          value: "http://opentelemetry-collector.suse-observability.svc.cluster.local:4318"
        - name: COLLECT_GPU_STATS
          value: "false"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: test-genai-demo-service
  namespace: fresh
spec:
  selector:
    app: test-genai-demo
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP