{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ai-compare-suse.fullname" . }}-frontend-nginx
  labels:
    {{- include "ai-compare-suse.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  nginx.conf: |
    user nginx;
    worker_processes auto;
    
    error_log /var/log/nginx/error.log notice;
    pid /var/run/nginx.pid;
    
    events {
        worker_connections 1024;
    }
    
    http {
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        
        # Logging format for observability
        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for" '
                        'rt=$request_time uct="$upstream_connect_time" '
                        'uht="$upstream_header_time" urt="$upstream_response_time"';
        
        access_log /var/log/nginx/access.log main;
        
        sendfile on;
        tcp_nopush on;
        keepalive_timeout 65;
        gzip on;
        
        # Security headers
        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        
        server {
            listen 8080;
            server_name localhost;
            
            # Serve static frontend content
            location / {
                root /usr/share/nginx/html;
                index index.html;
                try_files $uri $uri/ /index.html;
                
                # Add observability headers
                add_header X-Frontend-Version "{{ .Chart.AppVersion }}";
                add_header X-Request-ID $request_id;
            }
            
            # Proxy API requests to backend
            location /api/ {
                proxy_pass http://{{ include "ai-compare-suse.fullname" . }}-app-service:{{ .Values.llmChat.service.port }}/api/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_set_header X-Request-ID $request_id;
                
                # Timeout settings
                proxy_connect_timeout 5s;
                proxy_send_timeout 8s;
                proxy_read_timeout 8s;
                
                # Buffer settings for better performance
                proxy_buffering on;
                proxy_buffer_size 4k;
                proxy_buffers 8 4k;
            }
            
            # Health check endpoint (proxied to backend)
            location /health {
                proxy_pass http://{{ include "ai-compare-suse.fullname" . }}-app-service:{{ .Values.llmChat.service.port }}/health;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Request-ID $request_id;
                
                access_log off;  # Reduce noise from health checks
            }
            
            # Metrics endpoint (proxied to backend)
            location /metrics {
                proxy_pass http://{{ include "ai-compare-suse.fullname" . }}-app-service:{{ .Values.llmChat.service.port }}/api/metrics;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Request-ID $request_id;
            }
            
            # Error pages
            error_page 500 502 503 504 /50x.html;
            location = /50x.html {
                root /usr/share/nginx/html;
            }
        }
    }
{{- end }}