apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-compare-suse.fullname" . }}-app-service
spec:
  selector:
    app: {{ include "ai-compare-suse.fullname" . }}-app
  ports:
  # Gradio UI port (7860)
  - protocol: TCP
    port: {{ .Values.aiCompare.service.port }}
    targetPort: {{ .Values.aiCompare.service.port }}
    name: gradio
  # HTTP API server port (8080) for frontend communication
  - protocol: TCP
    port: {{ .Values.aiCompare.httpApi.port }}
    targetPort: {{ .Values.aiCompare.httpApi.port }}
    name: http-api
  type: {{ .Values.aiCompare.service.type }}