# Default values for ai-compare chart

# -- Global image pull policy
imagePullPolicy: Always
# -- Default pull secrets (can be overridden, e.g., for SUSE chart)
imagePullSecrets: []
# -- Application settings
ollama:
  image:
    repository: ollama/ollama
    tag: "0.6.8"
  service:
    port: 11434
    type: ClusterIP
  gpu:
    enabled: false
  # -- Hardware Configuration for Ollama
  hardware:
    type: "nvidia" # Options: "nvidia", "apple"
  # -- Resource allocation for the main Ollama container
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "4"
      memory: "16Gi"
  persistence:
    enabled: false
    size: 10Gi
    storageClassName: "" # Use default if empty, or specify a storage class
  # Model caching options
  modelCache:
    # NFS-based model caching for shared storage across deployments
    nfs:
      enabled: false
      server: "10.0.9.10" # NFS server IP/hostname
      path: "/data/ai-models" # NFS share path for caching models
openWebui:
  image:
    repository: ghcr.io/open-webui/open-webui
    tag: "0.6.9" # Pipeline-enabled version
  service:
    port: 8080
    type: NodePort
  # Pipeline integration settings
  pipelines:
    enabled: true
    url: "http://pipelines-service:9099"
# Open WebUI Pipelines Service
pipelines:
  enabled: true
  image:
    repository: ghcr.io/open-webui/pipelines
    tag: "main"
  service:
    port: 9099
    type: ClusterIP
  # Pipeline deployment from git repo
  git:
    enabled: true
    repo: "https://github.com/wiredquill/ai-demos.git"
    branch: "main"
    path: "pipelines"
  # Pipeline configuration
  config:
    pipelineMode: "auto-cycle"
    logLevel: "INFO"
  # Auto-configuration settings
  autoConfig:
    enabled: true
    apiKey: "0p3n-w3bu!"
    modelId: "response_level"
    connectionName: "Response Level Pipeline"
llmChat:
  image:
    repository: ghcr.io/wiredquill/ai-demos
    tag: "35320f3"
  service:
    port: 7860
    type: NodePort
  persistence:
    enabled: false
    size: 10Gi
    storageClassName: "" # Use default if empty, or specify a storage class
  # Automation settings for the recurring test runner
  automation:
    enabled: false
    defaultPrompt: "Why is the sky blue? Be concise."
    intervalSeconds: 30
    sendMessages: true # Enable/disable sending test messages to models
  # Observability settings for OpenTelemetry and OpenLit
  observability:
    enabled: true
    otlpEndpoint: "http://opentelemetry-collector.suse-observability.svc.cluster.local:4318"
    collectGpuStats: true
    schedule: "*/5 * * * *"
# NeuVector Security Configuration
neuvector:
  enabled: false
  controllerUrl: "https://neuvector-svc-controller.neuvector.svc.cluster.local:10443"
  username: "admin"
  password: "admin"
