# This fleet.yaml defines the Git Repositories, Cluster Groups,
# and Bundles to deploy the llm-comm charts.

# This tells Fleet to create the following resources in the `fleet-default` namespace,
# which is the standard location for managing Fleet configurations for downstream clusters.
# You can bundle multiple resources into a single file using `---` as a separator.
apiVersion: v1
kind: List
items:
- apiVersion: fleet.cattle.io/v1alpha1
  kind: GitRepo
  metadata:
    name: llm-comm-suse-repo
    namespace: fleet-default
  spec:
    # IMPORTANT: Replace this with the URL to your Git repository
    repo: "https://github.com/SUSE-Technical-Marketing/suse-ai-demo.git"
    branch: main
    # This tells Fleet to only look for manifests inside this specific directory
    paths:
    - "/charts/llm-comm-suse"

- apiVersion: fleet.cattle.io/v1alpha1
  kind: GitRepo
  metadata:
    name: llm-comm-upstream-repo
    namespace: fleet-default
  spec:
    # IMPORTANT: Replace this with the URL to your Git repository
    repo: "https://github.com/SUSE-Technical-Marketing/suse-ai-demo.git"
    branch: main
    paths:
    - "/charts/llm-comm-upstream"

---
# This ClusterGroup targets any downstream cluster with the specific label for the SUSE deployment.
apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: llm-comm-suse-group
  namespace: fleet-default
spec:
  selector:
    matchLabels:
      'needs-llm-suse': 'true'

---
# This ClusterGroup targets any downstream cluster with the specific label for the Upstream deployment.
apiVersion: fleet.cattle.io/v1alpha1
kind: ClusterGroup
metadata:
  name: llm-comm-upstream-group
  namespace: fleet-default
spec:
  selector:
    matchLabels:
      'needs-llm': 'true'

---
# This Bundle links the SUSE git repo to the SUSE cluster group.
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: llm-comm-suse-bundle
  namespace: fleet-default
spec:
  # This references the GitRepo defined above
  repoName: llm-comm-suse-repo
  # This targets the ClusterGroup defined above
  targets:
  - clusterGroup: llm-comm-suse-group
  # This tells Fleet that the content is a Helm chart
  helm:
    # The chart name as defined in Chart.yaml
    chart: llm-comm-suse

---
# This Bundle links the Upstream git repo to the Upstream cluster group.
apiVersion: fleet.cattle.io/v1alpha1
kind: Bundle
metadata:
  name: llm-comm-upstream-bundle
  namespace: fleet-default
spec:
  repoName: llm-comm-upstream-repo
  targets:
  - clusterGroup: llm-comm-upstream-group
  helm:
    chart: llm-comm-upstream
