{{- if .Values.neuvector.enabled }}
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: {{ .Release.Namespace }}-{{ include "ai-compare.fullname" . }}
  labels:
    {{- include "ai-compare.labels" . | nindent 4 }}
spec:
  target:
    namespace: {{ .Release.Namespace }}
    service: {{ include "ai-compare.fullname" . }}
  dlp:
    status: true
    settings:
      - name: {{ include "ai-compare.fullname" . }}-dlp-sensor
        action: alert
  ingress:
    - action: allow
      name: Allow from Open WebUI
      selector:
        name: open-webui
    - action: allow
      name: Allow from Ollama
      selector:
        name: ollama
  egress:
    - action: allow
      name: Allow external traffic
      selector:
        name: external
{{- end }}
