apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm-chat-service-account
  labels:
    app: llm-chat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: llm-chat-configmap-manager
  labels:
    app: llm-chat
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "create", "update", "patch"]
  resourceNames: ["llm-chat-config"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llm-chat-configmap-binding
  labels:
    app: llm-chat
subjects:
- kind: ServiceAccount
  name: llm-chat-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: llm-chat-configmap-manager
  apiGroup: rbac.authorization.k8s.io