apiVersion: v1
entries:
  genai-observability-demo:
  - apiVersion: v2
    appVersion: latest
    created: "2025-10-31T18:06:58.727583-07:00"
    description: GenAI Observability Demo - Employee Question Generator and RAG Applications
    digest: 9f97ca3e3f67dc4e20898ac5a9f33c456532b4782ed178377b092f28cc21d605
    name: genai-observability-demo
    type: application
    urls:
    - https://raw.githubusercontent.com/SUSE-Technical-Marketing/suse-ai-demo/main/charts/genai-observability-demo-0.3.9.tgz
    version: 0.3.9
generated: "2025-10-31T18:06:58.724882-07:00"
