apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama-chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollama-chat-app
  template:
    metadata:
      labels:
        app: ollama-chat-app
    spec:
      containers:
        - name: chat-app
          image: "{{ .Values.llmChat.image.repository }}:{{ .Values.llmChat.image.tag }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.llmChat.service.port }}
          env:
            - name: OLLAMA_BASE_URL
              value: "http://ollama-service:11434"
            - name: OPEN_WEBUI_BASE_URL
              value: "http://open-webui-service:8080"
            # --- NEW ENVIRONMENT VARIABLES ---
            - name: AUTOMATION_ENABLED
              value: "{{ .Values.llmChat.automation.enabled }}"
            - name: AUTOMATION_PROMPT
              value: "{{ .Values.llmChat.automation.defaultPrompt }}"
            - name: AUTOMATION_INTERVAL
              value: "{{ .Values.llmChat.automation.intervalSeconds }}"
          volumeMounts:
            - name: config-volume
              mountPath: /app/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: chat-app-config