apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-compare-opentelemetry.fullname" . }}-app-service
  labels:
    app.kubernetes.io/name: {{ include "ai-compare-opentelemetry.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: genai-chat
    app.kubernetes.io/part-of: genai-stack
    ai.framework: "gradio-ollama"
    genai.application: "true"
  annotations:
    genai.observability/enabled: "true"
    genai.observability/type: "chat-application"
    genai.observability/models: "llama3.2:latest"
    genai.observability/framework: "ollama"
    observability.suse.com/genai-app: "true"
    ai.application.category: "conversational-ai"
spec:
  selector:
    app: {{ include "ai-compare-opentelemetry.fullname" . }}-app
  ports:
  # Gradio UI port (7860)
  - protocol: TCP
    port: {{ .Values.aiCompare.service.port }}
    targetPort: {{ .Values.aiCompare.service.port }}
    name: gradio
  # HTTP API server port (8080) for frontend communication
  - protocol: TCP
    port: {{ .Values.aiCompare.httpApi.port }}
    targetPort: {{ .Values.aiCompare.httpApi.port }}
    name: http-api
  type: {{ .Values.aiCompare.service.type }}