{{- if .Values.frontend.react.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-compare-opentelemetry.fullname" . }}-frontend-react-service
  annotations:
    description: "Service for React-based modern dashboard frontend"
    service.type: "frontend-ui"
  labels:
    {{- include "ai-compare-opentelemetry.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend-react
spec:
  selector:
    app: {{ include "ai-compare-opentelemetry.fullname" . }}-frontend-react
  ports:
    - port: {{ .Values.frontend.react.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  type: {{ .Values.frontend.react.service.type }}
  {{- if eq .Values.frontend.react.service.type "NodePort" }}
  {{- if .Values.frontend.react.service.nodePort }}
  nodePort: {{ .Values.frontend.react.service.nodePort }}
  {{- end }}
  {{- end }}
{{- end }}