{{- if .Values.neuvector.enabled }}
apiVersion: neuvector.com/v1
kind: NvSecurityRule
metadata:
  name: {{ .Release.Namespace }}-{{ include "ai-compare-suse.fullname" . }}
  labels:
    {{- include "ai-compare-suse.labels" . | nindent 4 }}
spec:
  target:
    selector:
      name: {{ .Release.Namespace }}.{{ include "ai-compare-suse.fullname" . }}
      criteria:
        - key: namespace
          op: "="
          value: {{ .Release.Namespace }}
        - key: service
          op: "="
          value: {{ include "ai-compare-suse.fullname" . }}
  dlp:
    status: true
    settings:
      - name: {{ include "ai-compare-suse.fullname" . }}-dlp-sensor
        action: allow
  ingress:
    - action: allow
      name: Allow from Open WebUI
      selector:
        name: open-webui
    - action: allow
      name: Allow from Ollama
      selector:
        name: ollama
  egress:
    - action: allow
      name: Allow external traffic
      selector:
        name: external
{{- end }}
