name: Publish Helm Charts to GitHub Releases

# Temporarily disabled - chart publishing not critical for main functionality
# Re-enable once repository permissions are properly configured for chart releases
on:
  # workflow_run:
  #   workflows: ["Build, Push, and Update K8s Manifests (upstream & SUSE)"]
  #   types:
  #     - completed
  #   branches:
  #     - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run Chart Releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: "true"
        with:
          charts_dir: charts

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .cr-index
          publish_branch: gh-pages
          force_orphan: true